#!/usr/bin/env python3
"""
LLM Prompt Runner

Dit script voert alle prompts uit de prompts/ folder uit op alle modellen
die gespecificeerd zijn in de config file. De gegenereerde code wordt
opgeslagen in de output directory.
"""

import sys
import json
from pathlib import Path
from datetime import datetime

from config import MODELS_TO_TEST, OUTPUT_DIR, PROMPTS_DIR
from prompts.loader import load_all_prompts
from core.ollama_client import check_ollama_running, get_available_models, send_prompt_to_model, extract_code_from_response

def save_generated_code(output_dir, model_name, prompt_id, code_content):
    """
    Sla de gegenereerde code op in een Python bestand.
    
    Args:
        output_dir: De base output directory
        model_name: Naam van het model
        prompt_id: ID van de prompt
        code_content: De gegenereerde code
    
    Returns:
        Pad naar het opgeslagen bestand
    """
    # Maak een veilige directory naam van het model
    safe_model_name = model_name.replace(":", "_").replace("/", "_")
    
    # Maak de output directory structuur
    model_dir = Path(output_dir) / safe_model_name
    model_dir.mkdir(parents=True, exist_ok=True)
    
    # Genereer bestandsnaam
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{prompt_id}_{timestamp}.py"
    filepath = model_dir / filename
    
    # Schrijf de code naar het bestand
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"# Generated by: {model_name}\n")
        f.write(f"# Prompt ID: {prompt_id}\n")
        f.write(f"# Generated at: {datetime.now().isoformat()}\n")
        f.write("#" * 70 + "\n\n")
        f.write(code_content)
    
    return filepath

def save_metadata(output_dir, results):
    """
    Sla metadata over de run op in een JSON bestand.
    
    Args:
        output_dir: De output directory
        results: List met resultaten
    
    Returns:
        Pad naar het metadata bestand
    """
    metadata = {
        "run_timestamp": datetime.now().isoformat(),
        "total_prompts": len(set(r["prompt_id"] for r in results)),
        "total_models": len(set(r["model_name"] for r in results)),
        "total_generations": len(results),
        "successful": sum(1 for r in results if r["status"] == "success"),
        "failed": sum(1 for r in results if r["status"] != "success"),
        "results": results
    }
    
    metadata_path = Path(output_dir) / f"metadata_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    return metadata_path

def run_all_prompts():
    """
    Hoofdfunctie die alle prompts op alle modellen uitvoert.
    """
    print("=" * 70)
    print("🚀 LLM Prompt Runner")
    print("=" * 70)
    
    # Check Ollama
    print("\n📡 Checking Ollama connection...")
    check_ollama_running()
    
    # Laad prompts
    print(f"\n📂 Loading prompts from '{PROMPTS_DIR}'...")
    prompts = load_all_prompts(PROMPTS_DIR)
    if not prompts:
        print("❌ ERROR: No prompts found in prompts/ folder")
        sys.exit(1)
    
    print(f"✅ Loaded {len(prompts)} prompt(s):")
    for prompt in prompts:
        print(f"   • {prompt.get('name', 'Unknown')} ({prompt.get('id')})")
    
    # Haal beschikbare modellen op
    print(f"\n🤖 Getting available models...")
    models = get_available_models(configured_models=MODELS_TO_TEST)
    print(f"✅ Will use {len(models)} model(s):")
    for model in models:
        print(f"   • {model}")
    
    # Bereken totaal aantal runs
    total_runs = len(prompts) * len(models)
    print(f"\n📊 Total runs to execute: {total_runs} ({len(prompts)} prompts × {len(models)} models)")
    
    # Maak output directory
    output_path = Path(OUTPUT_DIR)
    output_path.mkdir(parents=True, exist_ok=True)
    print(f"\n💾 Output directory: {output_path.absolute()}")
    
    # Voer alle prompts uit
    results = []
    run_count = 0
    
    print("\n" + "=" * 70)
    print("🔄 Starting execution...")
    print("=" * 70)
    
    for model_idx, model_name in enumerate(models, 1):
        print(f"\n{'='*60}")
        print(f"🤖 Model {model_idx}/{len(models)}: {model_name}")
        print(f"{'='*60}")
        
        for prompt in prompts:
            run_count += 1
            prompt_id = prompt.get('id', 'unknown')
            prompt_name = prompt.get('name', 'Unknown')
            
            print(f"\n   📝 [{run_count}/{total_runs}] Prompt: {prompt_name}")
            print(f"      Category: {prompt.get('category', 'N/A')}")
            
            result = {
                "model_name": model_name,
                "prompt_id": prompt_id,
                "prompt_name": prompt_name,
                "timestamp": datetime.now().isoformat(),
                "status": "error",
                "output_file": None,
                "error_message": None
            }
            
            try:
                # Stuur prompt naar model
                prompt_text = prompt.get('prompt', '')
                response = send_prompt_to_model(model_name, prompt_text)
                
                # Extract code uit response
                code_content = extract_code_from_response(response)
                
                # Sla code op
                output_file = save_generated_code(OUTPUT_DIR, model_name, prompt_id, code_content)
                
                result["status"] = "success"
                result["output_file"] = str(output_file)
                
                # Toon eerste paar regels als preview
                preview_lines = code_content.split('\n')[:5]
                preview = '\n'.join(preview_lines)
                if len(code_content) > 200:
                    preview += '\n   ...'
                
                print(f"   ✅ Success!")
                print(f"   📄 Saved to: {output_file.name}")
                print(f"   👁️  Preview:\n      {preview[:150]}...")
                
            except TimeoutError as e:
                result["status"] = "timeout"
                result["error_message"] = str(e)
                print(f"   ⏱️  Timeout: {e}")
                
            except ValueError as e:
                result["status"] = "parse_error"
                result["error_message"] = str(e)
                print(f"   📄 Parse Error: {e}")
                
            except Exception as e:
                result["status"] = "error"
                result["error_message"] = str(e)
                print(f"   💥 Error: {e}")
            
            results.append(result)
    
    # Sla metadata op
    print("\n" + "=" * 70)
    print("💾 Saving metadata...")
    metadata_file = save_metadata(OUTPUT_DIR, results)
    print(f"✅ Metadata saved to: {metadata_file.name}")
    
    # Samenvatting
    successful = sum(1 for r in results if r["status"] == "success")
    failed = len(results) - successful
    
    print("\n" + "=" * 70)
    print("📊 Execution Summary")
    print("=" * 70)
    print(f"Total runs:     {len(results)}")
    print(f"Successful:     {successful} ✅")
    print(f"Failed:         {failed} ❌")
    print(f"\nOutput directory: {output_path.absolute()}")
    print("=" * 70)
    print("🎉 Done!")
    print("=" * 70)

if __name__ == "__main__":
    run_all_prompts()
