#!/usr/bin/env python3
"""
LLM Prompt Runner

Dit script voert alle 20 ETL taken uit op alle modellen die gespecificeerd 
zijn in de config file. De gegenereerde code wordt opgeslagen in een 
gestructureerde folder per model en taak.
"""

import sys
import json
import shutil
from pathlib import Path
from datetime import datetime

from config import MODELS_TO_TEST, OUTPUT_DIR
from core.ollama_client import check_ollama_running, get_available_models, send_prompt_to_model, extract_code_from_response


def load_all_tasks(prompts_dir="prompts"):
    """
    Laad alle taken uit de prompts folder.
    Zoekt naar task_*/prompt.json bestanden.
    
    Returns:
        List van task dictionaries
    """
    tasks = []
    prompts_path = Path(prompts_dir)
    
    if not prompts_path.exists():
        print(f"❌ ERROR: Prompts directory '{prompts_dir}' not found")
        return tasks
    
    # Zoek alle task folders (task_01_missing_values, etc.)
    for task_dir in sorted(prompts_path.glob("task_*")):
        if task_dir.is_dir():
            prompt_file = task_dir / "prompt.json"
            if prompt_file.exists():
                try:
                    with open(prompt_file, 'r', encoding='utf-8') as f:
                        task_data = json.load(f)
                        # Voeg folder path toe voor later gebruik
                        task_data['task_folder'] = str(task_dir)
                        tasks.append(task_data)
                except Exception as e:
                    print(f"⚠️  Warning: Could not load {prompt_file}: {e}")
    
    return tasks


def save_task_artifacts(output_dir, model_name, task_id, code_content, task_folder):
    """
    Sla de gegenereerde code op en kopieer input data en test files.
    
    Args:
        output_dir: De base output directory
        model_name: Naam van het model
        task_id: ID van de taak
        code_content: De gegenereerde code
        task_folder: Pad naar de taak folder met input data
    
    Returns:
        Pad naar de taak folder
    """
    # Maak veilige directory namen
    safe_model_name = model_name.replace(":", "_").replace("/", "_")
    safe_task_id = task_id.replace(".", "_")
    
    # Maak de folder structuur: generated_code/<model>/<task>/
    task_dir = Path(output_dir) / safe_model_name / safe_task_id
    task_dir.mkdir(parents=True, exist_ok=True)
    
    # Sla gegenereerde code op als generated_script.py
    script_path = task_dir / "generated_script.py"
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(f"# Generated by: {model_name}\n")
        f.write(f"# Task ID: {task_id}\n")
        f.write(f"# Generated at: {datetime.now().isoformat()}\n")
        f.write("#" * 70 + "\n\n")
        f.write(code_content)
    
    # Kopieer input bestanden en test.py vanuit de task folder
    task_source = Path(task_folder)
    for file in task_source.glob("*"):
        if file.is_file() and file.name != "prompt.json":
            dest = task_dir / file.name
            shutil.copy2(file, dest)
    
    return task_dir


def save_metadata(output_dir, results):
    """
    Sla metadata over de run op in een JSON bestand.
    """
    metadata = {
        "run_timestamp": datetime.now().isoformat(),
        "total_tasks": len(set(r["task_id"] for r in results)),
        "total_models": len(set(r["model_name"] for r in results)),
        "total_generations": len(results),
        "successful": sum(1 for r in results if r["status"] == "success"),
        "failed": sum(1 for r in results if r["status"] != "success"),
        "results": results
    }
    
    metadata_path = Path(output_dir) / f"metadata_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    return metadata_path


def run_all_tasks():
    """
    Hoofdfunctie die alle 20 taken op alle modellen uitvoert.
    """
    print("=" * 70)
    print("🚀 LLM Prompt Runner - 20 ETL Tasks")
    print("=" * 70)
    
    # Check Ollama
    print("\n📡 Checking Ollama connection...")
    check_ollama_running()
    
    # Laad alle taken
    print(f"\n📂 Loading tasks from 'prompts/'...")
    tasks = load_all_tasks()
    if not tasks:
        print("❌ ERROR: No tasks found in prompts/ folder")
        sys.exit(1)
    
    print(f"✅ Loaded {len(tasks)} task(s):")
    for task in tasks:
        print(f"   • {task.get('name', 'Unknown')} ({task.get('id')})")
    
    # Haal beschikbare modellen op
    print(f"\n🤖 Getting available models...")
    models = get_available_models(configured_models=MODELS_TO_TEST)
    print(f"✅ Will use {len(models)} model(s):")
    for model in models:
        print(f"   • {model}")
    
    # Bereken totaal aantal runs
    total_runs = len(tasks) * len(models)
    print(f"\n📊 Total runs to execute: {total_runs} ({len(tasks)} tasks × {len(models)} models)")
    
    # Maak output directory
    output_path = Path(OUTPUT_DIR)
    output_path.mkdir(parents=True, exist_ok=True)
    print(f"\n💾 Output directory: {output_path.absolute()}")
    
    # Voer alle taken uit
    results = []
    run_count = 0
    
    print("\n" + "=" * 70)
    print("🔄 Starting execution...")
    print("=" * 70)
    
    for model_idx, model_name in enumerate(models, 1):
        print(f"\n{'='*60}")
        print(f"🤖 Model {model_idx}/{len(models)}: {model_name}")
        print(f"{'='*60}")
        
        for task in tasks:
            run_count += 1
            task_id = task.get('id', 'unknown')
            task_name = task.get('name', 'Unknown')
            task_folder = task.get('task_folder', '')
            
            print(f"\n   📝 [{run_count}/{total_runs}] Task: {task_name}")
            print(f"      Category: {task.get('category', 'N/A')}")
            print(f"      Difficulty: {task.get('difficulty', 'N/A')}")
            
            result = {
                "model_name": model_name,
                "task_id": task_id,
                "task_name": task_name,
                "timestamp": datetime.now().isoformat(),
                "status": "error",
                "output_folder": None,
                "error_message": None
            }
            
            try:
                # Stuur prompt naar model
                prompt_text = task.get('prompt', '')
                response = send_prompt_to_model(model_name, prompt_text)
                
                # Extract code uit response
                code_content = extract_code_from_response(response)
                
                # Sla code op en kopieer input files
                task_output_dir = save_task_artifacts(
                    OUTPUT_DIR, model_name, task_id, code_content, task_folder
                )
                
                result["status"] = "success"
                result["output_folder"] = str(task_output_dir)
                
                # Toon preview
                preview_lines = code_content.split('\n')[:3]
                preview = '\n'.join(preview_lines)
                if len(code_content) > 150:
                    preview += '\n   ...'
                
                print(f"   ✅ Success!")
                print(f"   📁 Saved to: {task_output_dir}")
                print(f"   👁️  Preview: {preview[:100]}...")
                
            except TimeoutError as e:
                result["status"] = "timeout"
                result["error_message"] = str(e)
                print(f"   ⏱️  Timeout: {e}")
                
            except ValueError as e:
                result["status"] = "parse_error"
                result["error_message"] = str(e)
                print(f"   📄 Parse Error: {e}")
                
            except Exception as e:
                result["status"] = "error"
                result["error_message"] = str(e)
                print(f"   💥 Error: {e}")
            
            results.append(result)
    
    # Sla metadata op
    print("\n" + "=" * 70)
    print("💾 Saving metadata...")
    metadata_file = save_metadata(OUTPUT_DIR, results)
    print(f"✅ Metadata saved to: {metadata_file.name}")
    
    # Samenvatting
    successful = sum(1 for r in results if r["status"] == "success")
    failed = len(results) - successful
    
    print("\n" + "=" * 70)
    print("📊 Execution Summary")
    print("=" * 70)
    print(f"Total runs:     {len(results)}")
    print(f"Successful:     {successful} ✅")
    print(f"Failed:         {failed} ❌")
    print(f"\nOutput directory: {output_path.absolute()}")
    print("=" * 70)
    print("🎉 Done! Run 'python evaluate.py' to test the generated code.")
    print("=" * 70)


if __name__ == "__main__":
    run_all_tasks()
