# Generated by: deepseek-coder-v2:latest
# Prompt ID: data_analysis_1
# Generated at: 2026-05-02T13:33:28.552429
######################################################################

import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate synthetic dataset
dates = pd.date_range(end='2023-12-31', periods=365)
products = ['A', 'B', 'C', 'D']
sales = np.random.randint(100, 1000, size=(1000,))
costs = np.random.randint(50, 500, size=(1000,))
data = {
    'datum': np.repeat(dates, len(products)),
    'product': np.tile(products, len(dates)),
    'verkoop': sales,
    'kosten': costs
}
df = pd.DataFrame(data)

# Calculate total revenue per product
total_revenue = df.groupby('product')['verkoop'].sum()

# Calculate average margin per product
df['marge'] = df['verkoop'] - df['kosten']
average_margin = df.groupby('product')['marge'].mean()

# Calculate standard deviation of sales per product
std_sales = df.groupby('product')['verkoop'].std()

# Calculate monthly trend of total sales
df['maand'] = df['datum'].dt.month
monthly_trend = df.groupby(['maand', 'product'])['verkoop'].sum().unstack(fill_value=0)

# Print results
print("Totale omzet per product:")
print(total_revenue)
print("\nGemiddelde marge per product:")
print(average_margin)
print("\nStandaarddeviatie van verkopen per product:")
print(std_sales)
print("\nMaandelijkse trend van totale verkopen:")
print(monthly_trend)