# Generated by: deepseek-coder-v2:latest
# Prompt ID: data_cleaning
# Generated at: 2026-05-02T13:34:06.545840
######################################################################

import pandas as pd
import numpy as np

# Maak een 'vuile' dataset met onderstaande vervuilde data
data = {
    'datum': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
    'waarde': [10, 20, np.nan, 40, 50],
    'categorie': ['A', 'B', 'C', 'D', 'E'],
    'beschrijving': ['some text ', ' another text', 'yet another text', 'duplicate', 'duplicate']
}

df = pd.DataFrame(data)

# Functie om ontbrekende waarden te behandelen
def handle_missing_values(df):
    df['waarde'].fillna(df['waarde'].mean(), inplace=True)
    return df

# Functie om duplicaten te verwijderen
def remove_duplicates(df):
    df.drop_duplicates(inplace=True)
    return df

# Functie om datums naar ISO formaat te normaliseren
def normalize_dates(df):
    df['datum'] = pd.to_datetime(df['datum']).dt.strftime('%Y-%m-%d')
    return df

# Functie om outliers met IQR methode te detecteren en te verwijderen
def remove_outliers(df):
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    cleaned_df = df[(df >= lower_bound) & (df <= upper_bound)]
    return cleaned_df

# Functie om whitespace te trimmen in tekstkolommen
def trim_whitespace(df):
    for column in df.select_dtypes([object]):
        if df[column].dtype == "object":
            df[column] = df[column].str.strip()
    return df

# Functie om categorische waarden naar lowercase te normaliseren
def normalize_categories(df):
    for column in df.select_dtypes([object]):
        if df[column].dtype == "object":
            df[column] = df[column].str.lower()
    return df

# Pipeline voor data cleaning
def clean_data(df):
    print("Original DataFrame:")
    print(df)
    
    df = handle_missing_values(df)
    df = remove_duplicates(df)
    df = normalize_dates(df)
    df = trim_whitespace(df)
    df = normalize_categories(df)
    
    print("\nCleaned DataFrame:")
    print(df)

# Voer de cleaning pipeline uit
clean_data(df)