# Generated by: deepseek-coder-v2:latest
# Prompt ID: etl_basic
# Generated at: 2026-05-02T13:34:48.846322
######################################################################

import pandas as pd

def load_data(file_path):
    try:
        data = pd.read_csv(file_path)
        return data
    except Exception as e:
        print(f"Error loading data from file {file_path}: {e}")
        return None

def transform_data(df):
    try:
        df['leeftijd'] = df['leeftijd'].astype(int)
        df['salaris'] = df['salaris'].str.replace('€', '').astype(float)
        
        conditions = [
            (df['leeftijd'] < 30),
            (df['leeftijd'] >= 30) & (df['leeftijd'] <= 50),
            (df['leeftijd'] > 50)
        ]
        choices = ['jong', 'midden', 'oud']
        
        df['leeftijdsgroep'] = pd.np.select(conditions, choices, default='unknown')
        df = df[df['salaris'] > 30000]
        
        return df
    except Exception as e:
        print(f"Error transforming data: {e}")
        return None

def save_data(df, file_path):
    try:
        df.to_csv(file_path, index=False)
    except Exception as e:
        print(f"Error saving data to file {file_path}: {e}")

# Main ETL process
def etl_process(input_file, output_file):
    data = load_data(input_file)
    if data is not None:
        transformed_data = transform_data(data)
        if transformed_data is not None:
            save_data(transformed_data, output_file)

# Example usage
etl_process('input.csv', 'output.csv')