# Generated by: deepseek-coder-v2:latest
# Prompt ID: etl_api
# Generated at: 2026-05-02T13:34:26.890071
######################################################################

import requests
import json

def fetch_data():
    url = 'https://jsonplaceholder.typicode.com/users'
    try:
        response = requests.get(url, timeout=5)
        response.raise_for_status()  # Raise an error for bad status codes
        data = response.json()
        return data
    except requests.Timeout:
        print("Request timed out")
    except requests.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"An error occurred: {err}")

def transform_data(users):
    transformed = []
    for user in users:
        new_user = {
            'id': user['id'],
            'volledige_naam': user['name'],
            'email': user['email'],
            'stad': user['address']['city'],
            'bedrijf': user['company']['name']
        }
        transformed.append(new_user)
    return transformed

def filter_and_sort_data(users):
    filtered = [user for user in users if user['stad'].startswith('G')]
    sorted_by_company = sorted(filtered, key=lambda x: x['bedrijf'])
    return sorted_by_company

def save_to_file(data, filename='output.json'):
    with open(filename, 'w') as file:
        json.dump(data, file, indent=4)

# Main execution
if __name__ == "__main__":
    users = fetch_data()
    if users:
        transformed_users = transform_data(users)
        filtered_and_sorted_users = filter_and_sort_data(transformed_users)
        save_to_file(filtered_and_sorted_users)