# Generated by: deepseek-coder-v2:latest
# Prompt ID: sql_etl
# Generated at: 2026-05-02T13:35:30.710699
######################################################################

import sqlite3
import pandas as pd
from datetime import datetime

# Create an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create the 'verkopen' table
cursor.execute('''CREATE TABLE verkopen (id INTEGER PRIMARY KEY, product TEXT, categorie TEXT, prijs REAL, aantal INTEGER, verkoop_datum DATE)''')

# Insert 50 example records
import random
products = ['Product A', 'Product B', 'Product C', 'Product D', 'Product E']
categories = ['Category 1', 'Category 2', 'Category 3', 'Category 4', 'Category 5']
dates = [datetime.now() - pd.DateOffset(months=x) for x in range(60, 0, -1)]

for _ in range(50):
    id_ = random.randint(1, 1000)
    product = random.choice(products)
    categorie = random.choice(categories)
    prijs = round(random.uniform(10, 100), 2)
    aantal = random.randint(1, 10)
    verkoop_datum = random.choice(dates)
    cursor.execute('''INSERT INTO verkopen (id, product, categorie, prijs, aantal, verkoop_datum) VALUES (?, ?, ?, ?, ?, ?)''', (id_, product, categorie, prijs, aantal, verkoop_datum))

conn.commit()

# Perform SQL analyses
total_omzet = pd.read_sql_query('SELECT categorie, SUM(prijs * aantal) AS total_sales FROM verkopen GROUP BY categorie', conn)
top_products = pd.read_sql_query('SELECT product, SUM(aantal) AS total_sold FROM verkopen GROUP BY product ORDER BY total_sold DESC LIMIT 5', conn)
laatste_maanden = datetime.now().date().replace(day=1) - pd.DateOffset(months=6)
monthly_sales = pd.read_sql_query('SELECT strftime("%Y-%m", verkoop_datum) AS month, SUM(prijs * aantal) AS sales FROM verkopen WHERE verkoop_datum >= ? GROUP BY month', conn, params=(laatste_maanden,))
avg_order_value = pd.read_sql_query('SELECT categorie, AVG(prijs * aantal) AS avg_order_value FROM verkopen GROUP BY categorie', conn)

# Export results to CSV files
total_omzet.to_csv('total_omzet.csv', index=False)
top_products.to_csv('top_products.csv', index=False)
monthly_sales.to_csv('monthly_sales.csv', index=False)
avg_order_value.to_csv('avg_order_value.csv', index=False)

# Generate a summary report
summary = pd.DataFrame({
    'Total Omzet Per Categorie': total_omzet['total_sales'].sum(),
    'Top 5 Best Verkochte Producten Aantal': top_products['total_sold'].sum(),
    'Gemiddelde Orderwaarde Per Categorie': avg_order_value['avg_order_value'].mean()
})

summary.to_csv('summary_report.csv', index=False)

# Close the database connection
conn.close()